#!/usr/bin/env sh

WHOAMI=$(whoami)

pipenv run gunicorn -w 2 -b unix:/srv/apps/$WHOAMI/dev-$WHOAMI.sock \
    --pid /home/${WHOAMI::1}/${WHOAMI::2}/${WHOAMI}/hknweb/tmp/gunicorn.pid \
    --log-file - main:app
